-- AlterTable
ALTER TABLE "TeamInvite" ADD COLUMN "school" TEXT NOT NULL DEFAULT '';
ALTER TABLE "TeamInvite" ADD COLUMN "city" TEXT NOT NULL DEFAULT '';
ALTER TABLE "TeamInvite" ADD COLUMN "languages" TEXT NOT NULL DEFAULT '';
ALTER TABLE "TeamInvite" ADD COLUMN "availability" TEXT NOT NULL DEFAULT '';
ALTER TABLE "TeamInvite" ADD COLUMN "heardFrom" TEXT NOT NULL DEFAULT '';
ALTER TABLE "TeamInvite" ADD COLUMN "superpower" TEXT NOT NULL DEFAULT '';
